-- Intentionally empty. This file is applied unconditionally by
-- run-tests.sh before the numbered assertion suite in supabase/tests/,
-- but none of those files depend on it -- each one creates its own
-- self-contained fixtures (organizations, users, vehicles) under its own
-- UUIDs, verified by running the full suite with and without the fixture
-- rows this file used to contain. Kept as an empty file rather than
-- deleted so run-tests.sh's unconditional `psql < seed.sql` step keeps
-- working without a script change.
